# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/wangyiyang/Magic-Terminal

  goconst:
    min-len: 3
    min-occurrences: 3

  dupl:
    threshold: 100

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 20

  gocyclo:
    min-complexity: 15

  godot:
    scope: declarations
    capital: true

  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign

  gomodguard:
    blocked:
      modules: []

  gosec:
    includes:
      - G401
      - G501
      - G502
    excludes:
      - G104

  lll:
    line-length: 120

  maligned:
    suggest-new: true

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  unparam:
    check-exported: false

  unused:
    check-exported: false

  whitespace:
    multi-if: false
    multi-func: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocyclo

    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters:
        - gochecknoinits
        - gocognit
        - funlen

  # Maximum issues count per one linter. Set to 0 to disable.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable.
  max-same-issues: 0

  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  new: false

  # Fix found issues (if it's supported by the linter).
  fix: false
