[Details]
  Icon = "data/Icon.png"
  Name = "Magic Terminal"
  ID = "com.wangyiyang.magicterminal"

[Source]
  Repo = "https://github.com/wangyiyang/Magic-Terminal"
  Dir = "cmd/fyneterm"

[Migrations]
  fyneDo = true

